; ═══════════════════════════════════════════════════════════════
; Eco-Light & Space Optimizer — ESP32 IoT Side
; Kelompok IF-4MC-07 | Polibatam 2026
; Anggota IoT: Ruth Yohana Manurung
; ═══════════════════════════════════════════════════════════════

[env:esp32dev]
platform   = espressif32
board      = esp32dev
framework  = arduino

; ── PORT ────────────────────────────────────────────────────
upload_port   = COM15
monitor_port  = COM15
monitor_speed = 115200
upload_speed  = 115200

; ── LIBRARY ─────────────────────────────────────────────────
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.5

; ── BUILD ───────────────────────────────────────────────────
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM=0